name: Deploy Proxy Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Codespace
        uses: actions/setup-codespace@v1

      - name: Install Dependencies
        run: |
          npm install  # Assuming you're using Node.js

      - name: Start Proxy Server
        run: |
          node server.js  # Replace 'server.js' with your server file
